spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oad2f9lm1tDEZUCf0h7
            client-secret: G2Gh5INi8aVgtbI391ssmfLRcxu4vXHk1wa2I36V
        provider:
          okta:
            authorization-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/keys